# Generated by Django 5.2.5 on 2025-11-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items-%Y-%m-%d-'),
        ),
    ]
