# Generated by Django 5.2.5 on 2025-11-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_itemphoto_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="type",
            field=models.CharField(
                choices=[("Sell", "Venda"), ("Donation", "Doação"), ("Trade", "Troca")],
                default="Sell",
                max_length=20,
            ),
        ),
    ]
