# Generated by Django 5.2.5 on 2025-11-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_item_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="trade_interest",
            field=models.TextField(blank=True, null=True),
        ),
    ]
