# Generated by Django 5.2.5 on 2025-11-19 00:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userprofile_bio_alter_userprofile_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'item')},
        ),
        migrations.AlterModelTable(
            name='favorite',
            table='favorite',
        ),
    ]
