# Generated by Django 5.2.5 on 2025-11-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemphoto',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
