# Generated by Django 5.2.5 on 2025-11-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_favorite_unique_together_alter_favorite_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemphoto',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
