# Generated by Django 5.1.3 on 2025-11-23 23:04

# from django.db import migrations


# class Migration(migrations.Migration):

#     dependencies = [
#         ('api', '0008_alter_itemphoto_image'),
#     ]

#     operations = [
#         migrations.AlterModelTable(
#             name='notification',
#             table='notification',
#         ),
#     ]
