# .github/workflows/ci.yml
name: Frontend E2E (Cypress)

on:
  push:
    branches: [ main, Tests, Postman ]
  pull_request:
    branches: [ main, Tests ]

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      