name: API Tests (Postman/Newman)

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  postman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- Setup Python / instalar backend ---
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install backend deps
        working-directory: backend
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          nohup python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 &

      - name: Wait for API
        run: |
          for i in {1..30}; do
            if curl -sf http://127.0.0.1:8000/docs >/dev/null; then
              echo "API is up"; exit 0
            fi
            echo "Waiting API... ($i)"; sleep 2
          done
          echo "API did not start"; exit 1

      # --- Setup Node / Newman ---
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Newman
        run: npm i -g newman newman-reporter-htmlextra

      - name: Run Postman tests
        run: |
          mkdir -p reports/postman
          newman run tests/postman/postman_collection.json \
            -e tests/postman/postman_environment_local.json \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export reports/postman/report.html

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: postman-report
          path: reports/postman/report.html
          retention-days: 7
