name: API & Postman Tests

on:
  push:
    branches: [ main, Tests, Postman ]
  pull_request:
    branches: [ main, Tests ]

jobs:
  test-all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare reports dir
        run: mkdir -p reports

      # ===== Backend (pytest) =====
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'   # mantém compatível com seu projeto

      - name: Install backend deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pytest pytest-django

      - name: Run Django tests
        run: |
          pytest -q \
            --junitxml=reports/django-junit.xml
        working-directory: backend

      # ===== Postman (Newman) =====
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman
        run: npm i -g newman

      - name: Run Postman tests
        run: |
          newman run tests/postman/postman_collection.json \
            -e tests/postman/postman_environment_local.json \
            --reporters cli,junit \
            --reporter-junit-export reports/postman-junit.xml

      # ===== Artifacts =====
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: reports/
          retention-days: 7
